### ISSUE TITLE
Paper Result Reproduce

### ISSUE THREAD

**Issue by jiange91** [microsoft/ParrotServe#7]
Hi, very impressive work. I wonder if you can guide me in porting Meta-GPT into your system. I mainly want to reproduce the result in the paper and play around with it, Thx!

**Comment by SiriusNEO** [comment]
Hi @jiange91, thanks for your interest in our project. If you want to reproduce the result in our paper, you can try the [artifact branch](https://github.com/microsoft/ParrotServe/tree/artifact).

But since we did a project refactoring after submitting the paper, there is a gap between our main branch (V3) and the artifact branch (V2). V2 is a little hacky but we use this older version for the sake of reproducibility. For V3, we haven't deployed some experiments but we will soon do it.

And for our experiment 8.4 (Multi-agent Applications), what we did is building a workflow using Parrot frontend manually instead of integrating MetaGPT into Parrot. About how to use Parrot frontend in V3, there are some [examples](https://github.com/microsoft/ParrotServe/tree/main/examples). We're sorry we don't have documentation available at this time but I'll get it online as soon as I can.

If you have any other questions, feel free to email me! Hope this helps.
